# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-01 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160325_2151'),
        ('comments', '0002_auto_20170630_0815'),
    ]

    operations = [
    ]
