# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-01 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160412_0554'),
        ('posts', '0004_auto_20170626_2007'),
        ('posts', '0004_auto_20170630_0752'),
    ]

    operations = [
    ]
